# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-12-21 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horoscope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signo', models.CharField(max_length=20)),
                ('palabra', models.CharField(max_length=20)),
            ],
        ),
    ]
