# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-12-27 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horoscope',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Nop', max_length=1),
        ),
    ]
