# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-12-27 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0007_auto_20181226_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horoscope',
            old_name='Temas',
            new_name='palabra',
        ),
    ]
