# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-12-27 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0008_auto_20181226_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horoscope',
            name='palabra',
            field=models.CharField(max_length=20),
        ),
    ]
