# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-12-27 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0010_auto_20181227_1347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextoHoroscopo',
        ),
    ]
