# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-12-27 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0012_auto_20181227_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horoscope',
            name='usuario',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='prediccion.Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='name',
            field=models.CharField(blank=True, default='', max_length=20, null=True, unique=True),
        ),
    ]
