# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-12-27 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0014_auto_20181227_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='chicho@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='name',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
